<%@ Page Title="" Language="C#" MasterPageFile="~/masters/produccion.Master" AutoEventWireup="true"  EnableEventValidation="false" CodeBehind="Idioma.aspx.cs" Inherits="Gui.produccion.Idioma" %>

<%@ Register Src="~/controles/LabelTexto.ascx" TagPrefix="uc1" TagName="LabelTexto" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="TituloPagina2" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="card shadow w-50 mx-auto my-auto">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">
                  <asp:Label ID="LblIdiomaTitulo" runat="server"></asp:Label>
              </h6>
            </div>
            <div class="card-body">

                    <div class="form-group w-75 mx-auto">
                                <uc1:LabelTexto runat="server" ID="LtNombre" />
                                <uc1:LabelTexto runat="server" ID="LtCodigoIdioma" />
                                <asp:Button ID="BtnAgregarIdioma" runat="server" CssClass="btn btn-primary" OnClick="CrearIdioma_Click"/>
                    </div>
       
                <div class="table-responsive w-75 mx-auto">
                    <asp:GridView ID="GrillaIdiomas" runat="server" CssClass="table table-bordered" AutoGenerateColumns="true"
                        AutoGenerateSelectButton="true"
                        AutoGenerateDeleteButton="false" 
                        AutoGenerateEditButton="false" 
                        OnRowDeleting="BorrarIdioma_Click" 
                        OnRowEditing="EditarIdioma_Click"
                        OnRowUpdating="ActualizarIdioma_Click" 
                        OnRowCancelingEdit="CancelarIdioma_Click">
                        <SelectedRowStyle CssClass="table-success"/>
                    </asp:GridView>
                    <asp:Button ID="BtnAgregarDetalleIdioma" runat="server" CssClass="btn btn-primary" OnClick="AgregarDetalleIdioma_Click"/>
                </div>
            </div> 
        </div>
</asp:Content>
