<%@ Page Title="" Language="C#" MasterPageFile="~/masters/produccion.Master" AutoEventWireup="true" EnableEventValidation="false" CodeBehind="IdiomaDetalle.aspx.cs" Inherits="Gui.produccion.IdiomaDetalle" %>

<%@ Register Src="~/controles/Mensaje.ascx" TagPrefix="uc1" TagName="Mensaje" %>


<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="CardTitulo" runat="server">
    <asp:Label ID="LblIdiomaSeleccionado" runat="server"></asp:Label>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="CardBody" runat="server">
    <div class="table-responsive w-75 mx-auto scrolling-table-container2">
        <asp:GridView ID="Grilla" runat="server" CssClass="table table-bordered" AutoGenerateColumns="false"
            AutoGenerateSelectButton="false"
            AutoGenerateDeleteButton="false"
            AutoGenerateEditButton="true"
            OnRowDeleting="Borrar_Click"
            OnRowEditing="Editar_Click"
            OnRowUpdating="Actualizar_Click"
            OnRowUpdated="Actualizado_Click"
            OnRowCancelingEdit="Cancelar_Click">
            <SelectedRowStyle CssClass="table-success" />
            <Columns>
                <asp:BoundField DataField="Key" HeaderText="Clave" InsertVisible="false" ReadOnly="true" />
                <asp:TemplateField HeaderText="Traducción">
                    <ItemTemplate>
                        <%# Eval("Value") %>
                    </ItemTemplate>
                    <EditItemTemplate>
                        <asp:TextBox ID="TxtEditar" runat="server" Text='<%# Eval("Value") %>' />
                    </EditItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>
    </div>
</asp:Content>

<asp:Content ID="Content4" ContentPlaceHolderID="CardBotones" runat="server">
    <asp:Button ID="BtnCancelar" runat="server" Text="Cancelar" OnClick="CancelarBoton_Click" CssClass="btn btn btn-secondary m-1" />
    <asp:Button ID="BtnGuardar" runat="server" CssClass="btn btn-success m-1" OnClick="Guardar_Click" />
    <uc1:Mensaje runat="server" ID="Mensaje" />
</asp:Content>
