<%@ Page Title="" Language="C#" MasterPageFile="~/masters/produccion.Master" AutoEventWireup="true" EnableEventValidation="false" CodeBehind="Idioma.aspx.cs" Inherits="Gui.produccion.Idioma" %>

<%@ Register Src="~/controles/LabelTexto.ascx" TagPrefix="uc1" TagName="LabelTexto" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="CardTitulo" runat="server">
    <asp:Label ID="LblIdiomaTitulo" runat="server"></asp:Label>
</asp:Content>

<asp:Content ID="Content3" ContentPlaceHolderID="CardBody" runat="server">

    <div class="form-group w-75 mx-auto">
        <uc1:LabelTexto runat="server" ID="LtNombre" />
        <uc1:LabelTexto runat="server" ID="LtCodigoIdioma" />
        <asp:Button ID="BtnAgregarIdioma" runat="server" CssClass="btn btn-primary" OnClick="CrearIdioma_Click" />
    </div>
    <asp:GridView ID="GrillaIdiomas" runat="server" CssClass="table table-bordered" AutoGenerateColumns="true"
        AutoGenerateSelectButton="true"
        AutoGenerateDeleteButton="false"
        AutoGenerateEditButton="false"
        OnRowDeleting="BorrarIdioma_Click"
        OnRowEditing="EditarIdioma_Click"
        OnRowUpdating="ActualizarIdioma_Click"
        OnRowCancelingEdit="CancelarIdioma_Click">
        <SelectedRowStyle CssClass="table-success" />
    </asp:GridView>
</asp:Content>

<asp:Content ID="Content4" ContentPlaceHolderID="CardBotones" runat="server">
    <asp:Button ID="BtnModificar" runat="server" CssClass="btn btn-warning" OnClick="Modificar_Click" />
    <asp:Button ID="BtnAgregarDetalleIdioma" runat="server" CssClass="btn btn-primary" OnClick="AgregarDetalleIdioma_Click" />
</asp:Content>
