<%@ Page Title="" Language="C#" MasterPageFile="~/masters/produccion.Master" AutoEventWireup="true" EnableEventValidation="false" CodeBehind="IdiomaDetalle.aspx.cs" Inherits="Gui.produccion.IdiomaDetalle" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="CardTitulo" runat="server">
    <asp:Label ID="LblIdiomaSeleccionado" runat="server"></asp:Label>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="CardBody" runat="server">
    <asp:GridView ID="Grilla" runat="server" CssClass="table table-bordered scrolling-table-container" AutoGenerateColumns="false"
        AutoGenerateSelectButton="false"
        AutoGenerateDeleteButton="false"
        AutoGenerateEditButton="true"
        OnRowDeleting="Borrar_Click"
        OnRowEditing="Editar_Click"
        OnRowUpdating="Actualizar_Click"
        OnRowUpdated="Actualizado_Click"
        OnRowCancelingEdit="Cancelar_Click">
        <SelectedRowStyle CssClass="table-success" />
        <Columns>
            <asp:BoundField DataField="Key" HeaderText="Clave" InsertVisible="false" ReadOnly="true" />
            <asp:TemplateField HeaderText="Traducción">
                <ItemTemplate>
                    <%# Eval("Value") %>
                </ItemTemplate>
                <EditItemTemplate>
                    <asp:TextBox ID="TxtEditar" runat="server" Text='<%# Bind("Value") %>' />
                </EditItemTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
</asp:Content>

<asp:Content ID="Content4" ContentPlaceHolderID="CardBotones" runat="server">
    <asp:Button ID="BtnGuardar" runat="server" CssClass="btn btn-primary" OnClick="Guardar_Click" />
</asp:Content>
